config/routes.rb
Cv::Application.routes.draw do
  

  
  get "errors/index"

  resources :records_locations, :records_descriptions, :descriptions, :companies, :industries, :locations, :records, :schools, :job_titles, :education_records

  get 'skills/:skill', to: 'records#index', as: 'skill'
  get 'teachings/:teaching', to: 'schools#index', as: 'teaching'
  get 'tags/:tag', to: 'records#index', as: 'tag'
  
  
  root to: 'cv#index'
  
  match "linked_in/:action" => "linked_in##{:action}"
  match "linked_in" => "linked_in#index"
  
  
  

  
  match "/403", :to => "errors#index"
  match "/404", :to => "errors#page_not_found"
  match "/500", :to => "errors#index"
  
end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible :company_id, :end_date, :industry_id, :job_title_id, :link, :start_date, :is_current, :skill_list
  acts_as_taggable_on :skills
  belongs_to :company
  belongs_to :job_title
  has_many :records_locations
  has_many :locations, :through => :records_locations
  has_many :records_descriptions
  has_many :descriptions, :through => :records_descriptions, :order => "id ASC"
  
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  # GET /records.json
  def index
    @records = Record.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render json: @record, status: :created, location: @record }
      else
        format.html { render action: "new" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
  include ActsAsTaggableOn::TagsHelper
  
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date, :start_year => 1978 %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date, :start_year => 1978 %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :is_current %><br />
    <%= f.number_field :is_current %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.text_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :job_title_id %><br />
    <%= f.text_field :job_title_id %>
  </div>
  <div class="field">
    <%= f.label :skill_list, "Skills (separated by commas)" %><br />
    <%= f.text_field :skill_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records<span class="title_separator_light">:</span></h1>

<table>
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th>Link</th>
    <th>Is current?</th>
    <th>Company ID</th>
    <th>Job title ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @records.each do |record| %>
  <tr>
    <td><%= record.start_date %></td>
    <td><%= record.end_date %></td>
    <td><%= record.link %></td>
    <td><%= record.is_current %></td>
    <td><%= record.company_id %></td>
    <td><%= record.job_title_id %></td>
    <td><%= link_to 'Show', record %></td>
    <td><%= link_to 'Edit', edit_record_path(record) %></td>
    <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <tr>
		<td>Skills: <%= raw record.skill_list.map { |t| link_to t, skill_path(t) }.join(', ') %></td>
	</tr>
<% end %>
</table>

<br />
<div class="tag_cloud">
  <% tag_cloud Record.skill_counts.order('LOWER(name) ASC'), %w{s m l xl xxl} do |skill, css_class| %>
  	<%= link_to skill.name, skill_path(skill.name), class: css_class %>
	<% end %>
</div>
<br />

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New record<span class="title_separator_light">:</span></h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start date:</b>
  <%= @record.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @record.end_date %>
</p>

<p>
  <b>Link:</b>
  <%= @record.link %>
</p>
<p>
  <b>Is current?</b>
  <%= @record.is_current %>
</p>
<p>
  <b>Company ID:</b>
  <%= @record.company_id %>
</p>
<p>
  <b>Job title ID:</b>
  <%= @record.job_title_id %>
</p>
<p>
  <b>Skills</b>
	<%= @record.skill_list %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>