config/routes.rb
Cv::Application.routes.draw do
  

  
  get "errors/index"

  resources :records_locations, :records_descriptions, :descriptions, :companies, :industries, :locations, :records, :schools, :job_titles, :education_records

  get 'skills/:skill', to: 'records#index', as: 'skill'
  get 'teachings/:teaching', to: 'schools#index', as: 'teaching'
  get 'tags/:tag', to: 'records#index', as: 'tag'
  
  
  root to: 'cv#index'
  
  match "linked_in/:action" => "linked_in##{:action}"
  match "linked_in" => "linked_in#index"
  
  
  

  
  match "/403", :to => "errors#index"
  match "/404", :to => "errors#page_not_found"
  match "/500", :to => "errors#index"
  
end

app/models/job_title.rb
class JobTitle < ActiveRecord::Base
  attr_accessible :id, :title_long, :title_short
  has_many :records, :order => "end_date DESC"
  
end

app/controllers/job_titles_controller.rb
class JobTitlesController < ApplicationController
  # GET /job_titles
  # GET /job_titles.json
  def index
    @job_titles = JobTitle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @job_titles }
    end
  end

  # GET /job_titles/1
  # GET /job_titles/1.json
  def show
    @job_title = JobTitle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job_title }
    end
  end

  # GET /job_titles/new
  # GET /job_titles/new.json
  def new
    @job_title = JobTitle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job_title }
    end
  end

  # GET /job_titles/1/edit
  def edit
    @job_title = JobTitle.find(params[:id])
  end

  # POST /job_titles
  # POST /job_titles.json
  def create
    @job_title = JobTitle.new(params[:job_title])

    respond_to do |format|
      if @job_title.save
        format.html { redirect_to @job_title, notice: 'Job title was successfully created.' }
        format.json { render json: @job_title, status: :created, location: @job_title }
      else
        format.html { render action: "new" }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /job_titles/1
  # PUT /job_titles/1.json
  def update
    @job_title = JobTitle.find(params[:id])

    respond_to do |format|
      if @job_title.update_attributes(params[:job_title])
        format.html { redirect_to @job_title, notice: 'Job title was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_titles/1
  # DELETE /job_titles/1.json
  def destroy
    @job_title = JobTitle.find(params[:id])
    @job_title.destroy

    respond_to do |format|
      format.html { redirect_to job_titles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

app/views/job_titles/_form.html.erb
<%= form_for(@job_title) do |f| %>
  <% if @job_title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_title.errors.count, "error") %> prohibited this job_title from being saved:</h2>

      <ul>
      <% @job_title.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title_short %><br />
    <%= f.text_field :title_short %>
  </div>
  <div class="field">
    <%= f.label :title_long %><br />
    <%= f.text_field :title_long %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_titles/edit.html.erb
<h1>Editing job_title</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_title %> |
<%= link_to 'Back', job_titles_path %>

app/views/job_titles/index.html.erb
<h1>Listing job_titles</h1>

<table>
  <tr>
    <th>Title short</th>
    <th>Title long</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @job_titles.each do |job_title| %>
  <tr>
    <td><%= job_title.title_short %></td>
    <td><%= job_title.title_long %></td>
    <td><%= link_to 'Show', job_title %></td>
    <td><%= link_to 'Edit', edit_job_title_path(job_title) %></td>
    <td><%= link_to 'Destroy', job_title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job title', new_job_title_path %>

app/views/job_titles/new.html.erb
<h1>New job_title</h1>

<%= render 'form' %>

<%= link_to 'Back', job_titles_path %>

app/views/job_titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title short:</b>
  <%= @job_title.title_short %>
</p>

<p>
  <b>Title long:</b>
  <%= @job_title.title_long %>
</p>


<%= link_to 'Edit', edit_job_title_path(@job_title) %> |
<%= link_to 'Back', job_titles_path %>