config/routes.rb
Cv::Application.routes.draw do
  

  
  get "errors/index"

  resources :records_locations, :records_descriptions, :descriptions, :companies, :industries, :locations, :records, :schools, :job_titles, :education_records

  get 'skills/:skill', to: 'records#index', as: 'skill'
  get 'teachings/:teaching', to: 'schools#index', as: 'teaching'
  get 'tags/:tag', to: 'records#index', as: 'tag'
  
  
  root to: 'cv#index'
  
  match "linked_in/:action" => "linked_in##{:action}"
  match "linked_in" => "linked_in#index"
  
  
  

  
  match "/403", :to => "errors#index"
  match "/404", :to => "errors#page_not_found"
  match "/500", :to => "errors#index"
  
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  attr_accessible :link, :name, :short_name
  has_and_belongs_to_many :companies, :join_table => "industries_companies"
  has_many :records
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  # GET /industries
  # GET /industries.json
  def index
    @industries = Industry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @industries }
    end
  end

  # GET /industries/1
  # GET /industries/1.json
  def show
    @industry = Industry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @industry }
    end
  end

  # GET /industries/new
  # GET /industries/new.json
  def new
    @industry = Industry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @industry }
    end
  end

  # GET /industries/1/edit
  def edit
    @industry = Industry.find(params[:id])
  end

  # POST /industries
  # POST /industries.json
  def create
    @industry = Industry.new(params[:industry])

    respond_to do |format|
      if @industry.save
        format.html { redirect_to @industry, notice: 'Industry was successfully created.' }
        format.json { render json: @industry, status: :created, location: @industry }
      else
        format.html { render action: "new" }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /industries/1
  # PUT /industries/1.json
  def update
    @industry = Industry.find(params[:id])

    respond_to do |format|
      if @industry.update_attributes(params[:industry])
        format.html { redirect_to @industry, notice: 'Industry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1
  # DELETE /industries/1.json
  def destroy
    @industry = Industry.find(params[:id])
    @industry.destroy

    respond_to do |format|
      format.html { redirect_to industries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.erb
<%= form_for(@industry) do |f| %>
  <% if @industry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

      <ul>
      <% @industry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/industries/edit.html.erb
<h1>Editing industry</h1>

<%= render 'form' %>

<%= link_to 'Show', @industry %> |
<%= link_to 'Back', industries_path %>

app/views/industries/index.html.erb
<h1>Listing industries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Short name</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @industries.each do |industry| %>
  <tr>
    <td><%= industry.name %></td>
    <td><%= industry.short_name %></td>
    <td><%= industry.link %></td>
    <td><%= link_to 'Show', industry %></td>
    <td><%= link_to 'Edit', edit_industry_path(industry) %></td>
    <td><%= link_to 'Destroy', industry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Industry', new_industry_path %>

app/views/industries/new.html.erb
<h1>New industry</h1>

<%= render 'form' %>

<%= link_to 'Back', industries_path %>

app/views/industries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @industry.name %>
</p>

<p>
  <b>Short name:</b>
  <%= @industry.short_name %>
</p>

<p>
  <b>Link:</b>
  <%= @industry.link %>
</p>


<%= link_to 'Edit', edit_industry_path(@industry) %> |
<%= link_to 'Back', industries_path %>