config/routes.rb
Cv::Application.routes.draw do
  

  
  get "errors/index"

  resources :records_locations, :records_descriptions, :descriptions, :companies, :industries, :locations, :records, :schools, :job_titles, :education_records

  get 'skills/:skill', to: 'records#index', as: 'skill'
  get 'teachings/:teaching', to: 'schools#index', as: 'teaching'
  get 'tags/:tag', to: 'records#index', as: 'tag'
  
  
  root to: 'cv#index'
  
  match "linked_in/:action" => "linked_in##{:action}"
  match "linked_in" => "linked_in#index"
  
  
  

  
  match "/403", :to => "errors#index"
  match "/404", :to => "errors#page_not_found"
  match "/500", :to => "errors#index"
  
end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :link, :location_id, :logo_link, :name, :name_short
  has_many :education_records
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
    @tags = ActsAsTaggableOn::Tag.find(:all,
  	      :select => "#{ActsAsTaggableOn::Tag.table_name}.id, #{ActsAsTaggableOn::Tag.table_name}.name, COUNT(*) AS count",
          :joins  => "INNER JOIN taggings ON #{ActsAsTaggableOn::Tag.table_name}.id = #{ActsAsTaggableOn::Tagging.table_name}.tag_id",
          :group  => "#{ActsAsTaggableOn::Tag.table_name}.id HAVING COUNT(*) > 0",
          :order  => "LOWER(#{ActsAsTaggableOn::Tag.table_name}.name) ASC"
  	    )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date, :start_year => 1978 %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date, :start_year => 1978 %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name_short %><br />
    <%= f.text_field :name_short %>
  </div>
  <div class="field">
    <%= f.label :degree %><br />
    <%= f.text_field :degree %>
  </div>
  <div class="field">
    <%= f.label :degree_short %><br />
    <%= f.text_field :degree_short %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :logo_link %><br />
    <%= f.text_field :logo_link %>
  </div>
  <div class="field">
    <%= f.label :teaching_list, "Teachings (separated by commas)" %><br />
    <%= f.text_field :teaching_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/index.html.erb
<h1>Listing schools<span class="title_separator_light">:</span></h1>

<table>
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th>Name</th>
    <th>Name short</th>
    <th>Degree</th>
    <th>Degree short</th>
    <th>Link</th>
    <th>Logo link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schools.each do |school| %>
  <tr>
    <td><%= school.start_date %></td>
    <td><%= school.end_date %></td>
    <td><%= school.name %></td>
    <td><%= school.name_short %></td>
    <td><%= school.degree %></td>
    <td><%= school.degree_short %></td>
    <td><%= school.link %></td>
    <td><%= school.logo_link %></td>
    <td><%= link_to 'Show', school %></td>
    <td><%= link_to 'Edit', edit_school_path(school) %></td>
    <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <tr>
		<td>Teachings: <%= raw school.teaching_list.sort.map { |t| link_to t, teaching_path(t) }.join(', ') %></td>
	</tr>
<% end %>
</table>

<br />

<div class="tag_cloud">
  <% tag_cloud School.teaching_counts.order('name ASC'), %w{s m l} do |t, css_class| %>
  	<%= link_to t.name, teaching_path(t.name), class: css_class %>
	<% end %>
</div>

<br />

<div class="tag_cloud">
	<% tag_cloud @tags, %w{s m l xl xxl} do |t, css_class| %>
  	<%= link_to t.name, "#{root_path}tags/#{t.name}", class: css_class %>
	<% end %>
</div>

<br />

<%= link_to 'New School', new_school_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start date:</b>
  <%= @school.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @school.end_date %>
</p>

<p>
  <b>Name:</b>
  <%= @school.name %>
</p>

<p>
  <b>Name short:</b>
  <%= @school.name_short %>
</p>

<p>
  <b>Degree:</b>
  <%= @school.degree %>
</p>

<p>
  <b>Degree short:</b>
  <%= @school.degree_short %>
</p>

<p>
  <b>Link:</b>
  <%= @school.link %>
</p>

<p>
  <b>Logo link:</b>
  <%= @school.logo_link %>
</p>

<p>
  <b>Teachings</b>
	<%= @school.teaching_list %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>